from functools import cache
import sys
import logging

"""
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
sum_even = 0

@cache
def fibonacci(num = 32 + 1):
	global sum_even
	if num <= 1: return num == 1
	else: 
		num1 = fibonacci(num - 1)
		if num1 % 2 == 0: sum_even += num1
		return num1 + fibonacci(num - 2)

def main():
	fibonacci()
	print(sum_even)
if __name__ == '__main__': main()